# Change these first
owner: ignore-me-lol # Your GitHub organization or username, where this repository lives
repo: personal-uptime-monitor # The name of this repository
  
sites:
  - name: 'Personal: AA'
    url: https://aim.femboy.cafe
  - name: 'Rbux: Frontend'
    url: https://rbux.pw
  - name: 'Rbux: Backend'
    url: https://api.rbux.pw/app/leaderboard
  - name: 'Nexus: Landing'
    url: https://nexuspipe.com
  - name: 'Nexus: Docs'
    url: https://docs.nexuspipe.com
  - name: 'Nexus: Dashboard'
    url: https://dash.nexuspipe.com
  - name: 'Nexus: Fonts'
    url: https://fonts.nexus
  - name: 'Nexus: Fonts Legacy Domain'
    url: https://fonts.nexuspipe.com
  - name: 'Nexus: CDN.Fonts'
    url: https://cdn.fonts.nexus

status-website:
  theme: night
  cname: nup.expo.moe
  #baseUrl: /personal-nexus-uptime-monitor
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Personal Uptime Monitor
  introTitle: "**this** is my personal uptime monitoring utility for things."
  introMessage: contains uptime data for basically anything i care enough about to put in here - take ping with a massive grain of salt, as github runners are known to be slow
  navbar:
    - title: Status
      href: /

i18n:
  footer: Powered by [Upptime](https://upptime.js.org)
