# Change these first
owner: ignore-me-lol # Your GitHub organization or username, where this repository lives
repo: personal-uptime-monitor # The name of this repository

sites:
  - name: 'Personal: AA'
    url: https://aim.femboy.cafe
  - name: 'Nexus: Landing'
    url: https://nexuspipe.com
  - name: 'Nexus: Docs'
    url: https://docs.nexuspipe.com
  - name: 'Nexus: Dashboard'
    url: https://dash.nexuspipe.com
  - name: 'Nexus: Fonts'
    url: https://fonts.nexuspipe.com
  - name: 'Nexus: Fonts CDN'
    url: https://fonts-cdn.nexuspipe.com

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: nup.expo.moe
  #baseUrl: /personal-nexus-uptime-monitor
  logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  name: Personal Uptime Monitor
  introTitle: "**this** is my personal uptime monitoring utility for things."
  introMessage: contains uptime data for basically anything i care enough about to put in here
  navbar:
    - title: Status
      href: /

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
